### ISSUE TITLE
[if] Shortcode Pro v170220.78352-RC

### ISSUE THREAD

**Issue by raamdev** [websharks/if-shortcode-pro#3]
### Downloads

Please see the download links in Slack:
https://websharks.slack.com/archives/if-shortcode/p1487627335000012

### Changelog

v170220.78352-RC

- Bumping minimum required version of the WP Sharks Core.
- Bumping minimum required WordPress version to v4.6.
- Adding support for `wp-markdown-extra` filter configuration.
- Removing unnecessary nested shortcode callback handler. Starting with WP 4.6 the new `WP_Hook` class addresses the underlying problem this was solving. See [Issue #1](https://github.com/websharks/if-shortcode-pro/issues/1).
- Enhancing security be removing `basename(__FILE__)` from direct access notices.
- Removing unnecessary lite build variation from `.build.props` file.

### Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by renzms** [comment]
Tested

- [x] Enhancing security be removing basename(__FILE__) from direct access notices.
- [x] Bumping minimum required version of the WP Sharks Core.
- [x] Adding support for wp-markdown-extra filter configuration.
- [x] Removing unnecessary nested shortcode callback handler. Starting with WP 4.6 the new WP_Hook class addresses the underlying problem this was solving. See Issue #1.

- [x] Removing unnecessary lite build variation from .build.props file.

- [x] Bumping minimum required WordPress version to v4.6.

**Comment by renzms** [comment]
![screen shot 2017-02-23 at 10 08 32 pm](https://cloud.githubusercontent.com/assets/13220018/23262150/a58a04e8-fa14-11e6-9b26-e11128757463.png)

Should the notes regarding JetPack and Markdown be more visible? Such as a note underneath the option, rather than in the question mark pop-up? I feel like more casual users would miss this note. :)

Also, was unable to find WP Markdown Extra as a plugin, but according to [Jetpack](https://jetpack.com/support/markdown/), it utilizes it as a Writing Option.

> If you are already familiar with Markdown, just enable it on your blog and start writing; refer to the WordPress.com Markdown Quick Reference page for help. Jetpack uses **Markdown Extra**, which adds some features not originally available in Markdown. For best results, please use the Text tab in the Editor as the Visual editor can give unexpected results. See below for more details.

**Comment by renzms** [comment]
@jaswsinc @raamdev 

Everything seems to be working great. 

No bugs to report, is there anything else I should test specifically for failure?

The Markdown Extra + Jetpack support work awesome.

**Markdown Extra + Jetpack**
>![screen shot 2017-02-23 at 10 27 31 pm](https://cloud.githubusercontent.com/assets/13220018/23263034/df5b354a-fa17-11e6-9f51-c1170ab28482.png)


**Back End Shortcode**
>![screen shot 2017-02-23 at 10 30 01 pm](https://cloud.githubusercontent.com/assets/13220018/23263036/e05c2c10-fa17-11e6-9b66-494598ca1af9.png)

**Front end logged-in**
>![screen shot 2017-02-23 at 10 30 21 pm](https://cloud.githubusercontent.com/assets/13220018/23263037/e1952334-fa17-11e6-8b07-ce61107717b2.png)

**Front end logged-out**
>![screen shot 2017-02-23 at 10 31 30 pm](https://cloud.githubusercontent.com/assets/13220018/23263039/e2bc2960-fa17-11e6-9c47-fa7c67af8915.png)


This works for both conditions of Jetpack / Markdown Extra support since Markdown Extra is integrated with Jetpack.

>![screen shot 2017-02-23 at 10 36 13 pm](https://cloud.githubusercontent.com/assets/13220018/23263286/be31f0b0-fa18-11e6-839b-b1ad6e84e5b2.png)

>![screen shot 2017-02-23 at 10 36 29 pm](https://cloud.githubusercontent.com/assets/13220018/23263287/c0a661e6-fa18-11e6-829f-227e38bf9622.png)

When the option is off, Markdown is only supported outside the `if` shortcodes as intended.
>![screen shot 2017-02-23 at 10 36 43 pm](https://cloud.githubusercontent.com/assets/13220018/23263305/c908a4d4-fa18-11e6-94a0-5ce80017c155.png)
>
![screen shot 2017-02-23 at 10 36 57 pm](https://cloud.githubusercontent.com/assets/13220018/23263328/e17ec78c-fa18-11e6-8007-f45eca4a25fb.png)

**Comment by raamdev** [comment]
@renzms Thanks for the testing! That's all we need. :-) I'll put out a GA release soon.

**Comment by raamdev** [comment]
Republishing this RC, as I forgot to follow up here with a GA release. See https://github.com/websharks/if-shortcode-pro/issues/4.
